export const pseudocode: Record<string, string[]> = {
  "bubble-sort": [
    "for i from 0 to n-1",
    "  for j from 0 to n-i-1",
    "    if array[j] > array[j+1]",
    "      swap(array[j], array[j+1])",
    "return array",
  ],
  "selection-sort": [
    "for i from 0 to n-1",
    "  minIndex = i",
    "  for j from i+1 to n",
    "    if array[j] < array[minIndex]",
    "      minIndex = j",
    "  swap(array[i], array[minIndex])",
    "return array",
  ],
  "insertion-sort": [
    "for i from 1 to n",
    "  j = i",
    "  while j > 0 and array[j-1] > array[j]",
    "    swap(array[j-1], array[j])",
    "    j = j - 1",
    "return array",
  ],
  "quick-sort": [
    "quickSort(low, high):",
    "  if low >= high: return",
    "  pivotIndex = partition(low, high)",
    "  quickSort(low, pivotIndex - 1)",
    "  quickSort(pivotIndex + 1, high)",
    "",
    "partition(low, high):",
    "  pivot = array[high]",
    "  for j from low to high-1",
    "    if array[j] < pivot: swap(i, j)",
    "  swap(i+1, high)",
    "  return i + 1",
  ],
  "merge-sort": [
    "mergeSort(low, high):",
    "  if low >= high: return",
    "  mid = (low + high) / 2",
    "  mergeSort(low, mid)",
    "  mergeSort(mid+1, high)",
    "  merge(low, mid, high)",
    "",
    "merge(low, mid, high):",
    "  while left and right remain",
    "    take the smaller of the two",
    "  copy remaining elements",
  ],
  "heap-sort": [
    "buildMaxHeap()",
    "for i from n/2-1 down to 0: heapify(i)",
    "for i from n-1 down to 1",
    "  swap(array[0], array[i])",
    "  heapify(0, i)",
    "",
    "heapify(root, size):",
    "  find largest among root, left, right",
    "  if left/right > largest: update largest",
    "  if largest != root: swap and heapify(largest)",
  ],
  "linear-search": [
    "linearSearch(array, target):",
    "  for i from 0 to n-1",
    "    if array[i] == target",
    "      return i",
    "  return not found",
  ],
  "binary-search": [
    "binarySearch(array, target):",
    "  low = 0, high = n-1",
    "  while low <= high",
    "    mid = (low + high) / 2",
    "    if array[mid] == target",
    "      return mid",
    "    else if array[mid] < target",
    "      low = mid + 1",
    "    else",
    "      high = mid - 1",
    "  return not found",
  ],

  "counting-sort": [
    "countingSort(array):",
    "  for value in array: count[value]++",
    "  for i from 1 to max: count[i] += count[i-1]",
    "  for value in reverse(array):",
    "    count[value] -= 1",
    "    output[count[value]] = value",
    "  return output",
  ],
  "radix-sort": [
    "radixSort(array):",
    "  for exp = 1; max/exp > 0; exp *= 10",
    "    countingSortByDigit(array, exp)",
    "  return array",
    "",
    "countingSortByDigit(array, exp):",
    "  for value in array: count[digit(value,exp)]++",
    "  for value in reverse(array):",
    "    output[--count[digit]] = value",
    "  array = output",
  ],
};
